scan_to_scan_filter_chain:
  ros__parameters:
    filter1:
      name: box_filter
      type: laser_filters/LaserScanBoxFilter
      params:
        box_frame: base_link
        invert: false
        max_x: 0.3
        max_y: 0.215
        max_z: 1.0 
        min_x: -0.3
        min_y: -0.215
        min_z: -1.0

